---
version: "3"
silent: true

tasks:
  bootstrap:
    desc: fetch the pre-requisites for all workflows
    cmds:
      - echo 'nothing to do'

  release:patch:
    desc: create patch release
    cmds:
      - |
        npm run release -- -i patch --ci
  build:
    desc: build the package
    cmds:
      - npm run build
