on:
  push:
  #  tags:
  #    - "v[0-9]+.[0-9]+.[0-9]+"

name: ci

jobs:
  test:
    name: ci build & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the diamond-deploy repository
        uses: actions/checkout@v3
        with:
          repository: polysensus/diamond-deploy
          submodules: recursive

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          scope: "@polysensus"
          registry-url: "https://registry.npmjs.org"

      - name: build
        run: |
          npm install
          npm run lint
          npm run build

      - name: unit tests
        run: |
          echo "No tests defined yet ..."
